# menu子菜单可随意配置
menu:
  #Archives: /archives
  项目作品: /projects
  关于我: /aboutme
rss: /atom.xml
# description配置内容会出现在meta标签中，因此会被搜索引擎抓取
description: 
# 不填写的链接则不显示
social:
  weibo: http://weibo.com/u/2721279713
  github: https://github.com/futantan
  twitter: 
  google_plus:
  email: luckytantanfu@gmail.com 
# 封面中的头像
logo: /images/logo2.jpg
# cover处填写背景图片, color处填写覆盖层的颜色样式名
background:
  cover: /images/background-cover.jpg
  color: cover-slate

archive_date_format: MMM DD

# 多说的帐号名, 不配置则不启用
duoshuo_shortname: futantan

google_analytics: 
# 网站的favicon图片
favicon: /images/favicon.ico
